### ISSUE TITLE
Крутая галерея, но есть пару ньюансов

### ISSUE THREAD

**Issue by atalapov** [htmldiz/wp-theme-plug#1]
1) У галереи нет уникального идентификатора (получается у меня на одной и той же странице не может быть 2 галереи)
2) Галерею нельзя использовать для специфических шаблонов страниц (например, если нужно использовать только на главной странице или только на определенном шаблоне)

**Comment by otalapov** [comment]
У галереи нет уникального идентификатора (получается у меня на одной и той же странице не может быть 2 галереи)
